eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: https://iouri-eureka.cfapps.isg.hoopp.com/eureka/
  
  
