eureka:
  registration:
    enabled: true
  preferSameZone: true
  shouldUseDns: false
  decoderName: JacksonJson
  
---
spring:
  profiles: cloud
eureka:
  serviceUrl:
    default: https://iouri-eureka.cfapps.isg.hoopp.com/
---
spring:
  profiles: local
eureka:
  serviceUrl:
    default: http://localhost:8070/
