spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: https://iouri-eureka.cfapps.isg.hoopp.com/
---
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/
